### ISSUE TITLE
Cannot generate dihedral and orientation restraint for my peptide structure

### ISSUE THREAD

**Issue by nmt980** [dspoel/nmr2gmxpy#1]
Dear Sir,

I wanted to generate dihedral and orientation restraints using nmr2gmx.py tool for my peptide (PDB ID: 1NB1). But unfortunately it is giving me only distance restraint for my peptide. 

Could you please guide me. Help to get above mentioned files.

![Screenshot from 2021-09-18 00-20-09](https://user-images.githubusercontent.com/48363645/133839237-65c90684-023b-487f-bb77-176efdf7b4ab.png)

**Comment by dspoel** [comment]
It seems there are no dihedral and orientatation restraints in the experimental data file, 1nb1_mr.str.
