### ISSUE TITLE
Keep Getting ValueError: setting an array element with a sequence. when running nmr2gmx.py

### ISSUE THREAD

**Issue by msoconnor2** [dspoel/nmr2gmxpy#2]
Hello!

I cloned the repository to generate distance restraints for PDB ID: 2A36 but I keep getting this error when the script gets to the distance restraints portion of the script after running this command:

python nmr2gmx.py -n 2A36 -v

```
Traceback (most recent call last):
  File "nmr2gmxpy/nmr2gmx.py", line 483, in <module>
    include_file   = call_restraint_make_function(restraint_type, args.strfile,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "nmr2gmxpy/nmr2gmx.py", line 199, in call_restraint_make_function
    outf, nwritten, nrestraints = make_restraint_file(restraint_type, mr_file, verbose)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "nmr2gmxpy/nmr2gmx.py", line 182, in make_restraint_file
    res.read_file(mr_file)
  File "nmr2gmxpy/nmr2gmxpy_lib/Restraint_list.py", line 54, in read_file
    DR_array = np.array(DR_result_sets)
               ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```
The same issue account when I tried 1D3Z. The distance.itp file did not get produced for either protein. Additionally, I tried running the ./run_test.py and the the distance.itp files for those were not produced either. 

I installed PyNMRSTAR in a conda environment:
pip install pynmrstar

I'm using Python v 3.12.2 and numpy v 1.26.4 in a conda environment. 

Please let me know if I am doing anything wrong or I need more dependencies.

**Comment by dspoel** [comment]
So please git pull the updated version and try it. Please let me know if this solves your problem, I will then proceed to make a new release.

**Comment by dspoel** [comment]
Please see also this issue that I found will fixing the present one: https://github.com/dspoel/nmr2gmxpy/issues/3

**Comment by msoconnor2** [comment]
That worked thank you so much!
